const express = require("express")
const app = express()

const contactanos = require("./contactanos.routes")
const libro_reclamaciones = require("./libroreclamacion.routes")
const modal_branding = require("./modalbranding.routes")
const modal_desing = require("./modaldesing.routes")
const modal_gestion = require("./modalgestion.routes")
const modal_marketing = require("./modalmarketing.routes")
const person_caminos_5 = require("./personcamino5.routes")
const person_campaing_3 = require("./personcampaing3.routes")
const person_digi_1 = require("./persondigi1.routes")
const person_redes_4 = require("./personredes4.routes")
const person_web_2 = require("./personweb2.routes")
const posting_blog = require("./posting_blog.routes")
const usuarios = require("./usuarios.routes")

app.use("/contactanos", contactanos)
app.use("/libro-reclamaciones", libro_reclamaciones)
app.use("/modal-branding", modal_branding)
app.use("/modal-desing", modal_desing)
app.use("/modal-gestion", modal_gestion)
app.use("/modal-marketing", modal_marketing)
app.use("/person-caminos-5", person_caminos_5)
app.use("/person-campaing-3", person_campaing_3)
app.use("/person-digi-1", person_digi_1)
app.use("/person-redes-4", person_redes_4)
app.use("/person-web-2", person_web_2)
app.use("/posting_blog", posting_blog)
app.use("/usuarios", usuarios)


module.exports = app